# A parte superior do arquivo permanece a mesma
name: estante
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
# ... parte superior do arquivo ...

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 
  
# ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ---

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Use o hífen e liste a pasta. É a forma correta.

# ---

flutter_native_splash:
  color: "#277c7b"
  image: "assets/images/Livraria-Logo.png" # Caminho relativo dentro do projeto.