# pubspec.yaml
name: estante
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # Mantemos o seu SDK atual, mas note que ele está desatualizado (3.9.2)
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 
  supabase_flutter: ^2.5.0
  provider: ^6.1.1 

  
  # === ADIÇÕES NECESSÁRIAS PARA O PROJETO (CLEAN ARCHITECTURE E JSON) ===
  # Pacote para as anotações (@JsonSerializable)
  json_annotation: ^4.8.1
  
  # Pacote para requisições HTTP (Necessário para a futura feature de IA)
  http: ^1.2.1
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  # =====================================================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # === ADIÇÕES NECESSÁRIAS PARA O BUILD RUNNER (Geração de book.g.dart) ===
  build_runner: ^2.4.9
  json_serializable: ^6.8.0 
  # ======================================================================

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
